name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_dispatch:     # Enables manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/NotHarshhaa/devops-cheatsheet.git
          git fetch upstream

      - name: Merge upstream changes into fork
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || echo "No changes to merge"

      - name: Push changes back to your fork
        run: |
          git push origin main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
